Update Events with new event
BUComputingSociety/SocietyWebsite pull request #22
Opened 2017-12-15 18:45 UTC by BUComputingSociety

2017-12-17 19:52 UTC, waghorn requested changes

2017-12-17 19:52 UTC, waghorn commented on www/assets/events.xml
> +        <title>5 Star Society Xmas Party - Dec 2017</title>
I don't think this is the kind of event that we should be putting here. I should be ones we host ourselves

2018-01-09 00:53 UTC, iclefirefly12 commented
Changes made based on review by @waghorn

2018-01-24 15:37 UTC, waghorn approved these changes
Looks good

2018-01-24 15:37 UTC, merged